project_id = "nooeffvybuqwujdmhsvy"

[functions.analyze-tramite]
enabled = true
verify_jwt = false

[functions.send-push-notification]
enabled = true
verify_jwt = false

[functions.notify-tramite-change]
enabled = true
verify_jwt = false

[functions.send-broadcast-notification]
enabled = true
verify_jwt = false
